@startuml


    package Domain{
        interface Linter{
            Lint(files: List<File>): String
        }
        class SnakeLinter implements Linter{
        }


        class ExampleLinter2 implements Linter{
        }

        class PublicNonFinalFieldLinter implements Linter{
            +Lint(files: List<File>): String
        }


    }


    package Presentation{
        class LinterMain{
            Scanner scanner
            List<Linter> availableLinters
            +LoadLinters()
            -CallLinters(List<> Linter): String
            +DisplayResult(): void
        }
    }


    package DataStorage{
        class LinterLoader{
            loadLinter(path: String): Linter
        }


        class FileLoader{
            File file
        }
    }

 
    LinterMain ->"*" Linter
    LinterMain -d-> FileLoader
    LinterMain -d-> LinterLoader
   


    @enduml
